[package]
name = "bleveldb-sys"
version = "1.0.2"
links = "leveldb"
authors = ["NguyenDuck"]
description = "Rust FFI bindings for Mojang's fork of LevelDB (Bedrock Edition)"
edition = "2024"
license = "AGPL-3.0-only"
keywords = ["minecraft", "bedrock", "leveldb", "blocktopograph"]
repository = "https://github.com/Blocktopograph/bedrock-leveldb-sys"


[dependencies]
ffi-opaque = "2"
libc = "0.2"


[build-dependencies]
cc = "1.2"
glob = "0.3"
