[package]
name = "valentine_bedrock_1_21_130"
version = "0.1.0"
edition.workspace = true

[dependencies]
bitflags.workspace = true
bytes.workspace = true
uuid.workspace = true
valentine_bedrock_core.workspace = true
